---
stages:
  - install
  - build
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/softether-vpnsrv
  GH_REPOSITORY: SoftEtherVPN/SoftEtherVPN
  README_DESCRIPTION: |
    SoftEther VPN server in a container with pre-configured setup for networking.

include:
  - project: devops/pipes
    file: /templates/go.gitlab-ci.yml

  # - project: devops/pipes
  #   file: /templates/gh-release-tracker.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

gh-release-tracker:
  variables:
    TAGS_FILE: .tags

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  parallel:
    matrix:
      #- DOCKERFILE_NAME: Dockerfile-stable
      #  TAGS_FILE: '.tags'
      - DOCKERFILE_NAME: Dockerfile
        DOCKER_IMAGE_TAGS: latest-${GITLAB_CI_ARCH}
        GITLAB_CI_ARCH:
          - amd64
          - arm64
      - DOCKERFILE_NAME: Dockerfile-ubuntu
        DOCKER_IMAGE_TAGS: latest-ubuntu-${GITLAB_CI_ARCH}
        GITLAB_CI_ARCH:
          - amd64
          - arm64
  only:
    refs:
      - schedules
      - master
