---
stages:
  - publish
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/softether-vpnsrv
  GH_REPOSITORY: SoftEtherVPN/SoftEtherVPN
  README_DESCRIPTION: |
    SoftEther VPN server in a container with pre-configured setup for networking.

include:
  - project: devops/pipes
    file: /templates/gh-release-tracker.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

gh-release-tracker:
  variables:
    TAGS_FILE: .tags

build-docker-image:
  only:
    refs:
      - schedules
      - master
  parallel:
    matrix:
      - DOCKERFILE_NAME: Dockerfile
        TAGS_FILE: '.tags'
        TAG_AS_LATEST_FOR_BRANCHES_REGEX: |
          [ "master" ]
      - DOCKERFILE_NAME: Dockerfile-edge
        IMAGE_TAGS: edge
  rules:
    - if: $DOCKERFILE_NAME == "Dockerfile"
      allow_failure: true
