---
stages:
  - install
  - build
  - track
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/softether-vpnsrv
  DOCKER_USE_BUILDX: "true"
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64
  GH_REPOSITORY: SoftEtherVPN/SoftEtherVPN
  README_DESCRIPTION: |
    SoftEther VPN server in a container with pre-configured setup for networking.

include:
  - project: devops/pipes
    file: /templates/go.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/gh-release-tracker.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

gh-release-tracker:
  variables:
    TAGS_FILE: .tags

build-docker-image:
  parallel:
    matrix:
      #- DOCKERFILE_NAME: Dockerfile-stable
      #  TAGS_FILE: '.tags'
      - DOCKERFILE_NAME: Dockerfile
        DOCKER_IMAGE_TAGS: latest
      - DOCKERFILE_NAME: Dockerfile-ubuntu
        DOCKER_IMAGE_TAGS: latest
        DOCKER_IMAGE_TAGS_TEMPLATE: |
          [
            { "match": ".*", "template": "{{ index $0 }}-ubuntu"}
          ]
  only:
    refs:
      - schedules
      - master
