---
stages:
  - install
  - build
  - track
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/softether-vpnsrv
  GH_REPOSITORY: SoftEtherVPN/SoftEtherVPN
  README_DESCRIPTION: |
    SoftEther VPN server in a container with pre-configured setup for networking.

.publish-docker:
  stage: docker
  trigger:
    include:
      - project: devops/pipes
        file: /templates/docker-build-with-artifacts-dockerhub.gitlab-ci.yml
    strategy: depend

include:
  - project: devops/pipes
    file: /templates/go.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/gh-release-tracker.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

gh-release-tracker:
  variables:
    TAGS_FILE: .tags

build-docker-image:
  extends: .publish-docker
  parallel:
    matrix:
      #- DOCKERFILE_NAME: Dockerfile-stable
      #  TAGS_FILE: '.tags'
      - DOCKERFILE_NAME: Dockerfile
        DOCKER_IMAGE_TAGS: latest-${GITLAB_CI_ARCH}
        DOCKER_MANIFEST_TARGETS: ${DOCKER_IMAGE_NAME}:latest
        GITLAB_CI_ARCH:
          - amd64
          - arm64
      - DOCKERFILE_NAME: Dockerfile-ubuntu
        DOCKER_MANIFEST_TARGETS: ${DOCKER_IMAGE_NAME}:latest-ubuntu
        DOCKER_IMAGE_TAGS: latest-ubuntu-${GITLAB_CI_ARCH}
        GITLAB_CI_ARCH:
          - amd64
          - arm64
  only:
    refs:
      - schedules
      - master
