#!/bin/bash

source /scripts/logger.sh

log_interrupt "Terminating services..." "both"

log_warn "Shutting down SoftEther daemon..."
softether-vpnsrv stop >&/dev/null

log_warn "Removing tap software adapter..."
ip tuntap del dev tap_soft mode tap
ifconfig tap_soft down >&/dev/null

log_warn "Deleting SoftEther virtual network adapter..."
ip link delete tap_soft >&/dev/null

log_warn "Shutting down DNSMASQ daemon..."
pkill /usr/sbin/dnsmasq >&/dev/null

log_interrupt "Terminated services." "both"
